languageCode = "en-us"
title = "My New Hugo Site"

baseurl = "https://n3x-ai.github.io"
theme = "hello-friend-ng"

publishdir = "n3x-ai.github.io"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "N3X Academy of Research in Artificial Intelligence and Neural Systems"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"

[languages]
  [languages.en]
    title = "N3X Academy"
    subtitle = "A.I. Courses for a New Era."
    keywords = ""
    copyright = "All Rights Reserved for N3X Academy"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "N3X Academy"
      #logoHomeLink = "/img/logo.svg"
    # or
    #
    #path = "/img/logo.gif"
    #alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"